# Generated by Django 2.2.7 on 2020-04-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_auto_20200421_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='books',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
